version: "3"

services:
  registry:
    image: registry:2
    expose:
     - 5000
    environment:
      HTTP_PORT: 5000
      VIRTUAL_HOST: registry.s1.joffreybvn.be
      LETSENCRYPT_HOST: register.s1.joffreybvn.be
      LETSENCRYPT_EMAIL: "joffreybvn@gmail.com"
    networks:
      service_network:
    volumes:
      - nginx-certs:/etc/nginx/certs

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
